
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 6 moved the seed command out of package.json. Same effect as
    // the legacy `"prisma": { "seed": "..." }` block — runs on `db seed`
    // and on first `migrate dev` for a fresh database.
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
