
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 6 moved the seed command out of package.json. Compiler
    // options are forced inline because ts-node's auto-detection picks up
    // module: NodeNext in some environments (notably Alpine Node 24 inside
    // the Docker container), then fails because moduleResolution defaults
    // don't match. Pinning both ensures the seed runs identically in dev
    // and in the production container.
    seed: 'ts-node --transpile-only -O {"module":"commonjs","moduleResolution":"node"} prisma/seed.ts',
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
